name: iglu-fast-visual

global_settings:
  use_wandb: True

experiment_settings:
  save_every_sec: 120
  train_for_env_steps: 3000000000
  hidden_size: 512

async_ppo:
  # uncomment for better multi-gpu training
#  actor_worker_gpus: [1]
  rnn_type: gru
  experiment_summaries_interval: 20
  ppo_epochs: 1
  batch_size: 1024
  use_rnn: True
  max_grad_norm: 0.0
  
  num_workers: 32
  num_envs_per_worker: 16
  
environment:
  name: 'IGLUSilentBuilder-v0'
